### ISSUE TITLE
Projection issue

### ISSUE THREAD

**Issue by JMejuto** [michaelgrund/GMT-plotting#11]
Hi,

reproducing the code at least in the first two examples the same error arise:

mapproject [ERROR]: Cannot specify -J option with selected form of -G

Thank you

**Comment by michaelgrund** [comment]
Which GMT version do you use? All scripts work only with GMT versions >= 5.2.1 and < 6.0.0. Since the bash scripts are not maintained anymore, I recommend to use the corresponding Jupyter Notebooks in which [PyGMT](https://www.pygmt.org/latest/) is used to generate the plots.
